export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as RecoverPassword } from './RecoverPassword'
export { default as ResetPassword } from './ResetPassword'
export { default as SignUp } from './SignUp'
